# Generated by Django 4.1 on 2022-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalities',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
